import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'    
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clicic armina",
  description: "Generated by create next app",
  icons: '/next.svg'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ReactQueryClientProvider>
  );
}
