import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './globals.css'
import { FaViacoin } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Clicic armina",
  description: "Generated by create next app",
  icons: '/next.svg'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
